import { Inter } from "next/font/google";
import SideNav from "./components/sidenav";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Aryan Bhisikar | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="flex">
        <SideNav />
        {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
